
<RootWidget>:
    LoginScreen:
    CreateAccountScreen:

<LoginScreen>:
    name: "login"

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # WHITE
        Rectangle:
            pos: self.pos
            size: self.size

    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"

        BoxLayout:
            orientation: "vertical"
            size_hint: 0.9, 0.6
            spacing: dp(20)
            padding: dp(20)

            Label:
                text: "Login"
                bold: True
                color: 0.2, 0.6, 1, 1 # BLUE
                font_size: "36sp"
                halign: "center"
                theme_text_color: "Primary"
                size_hint_y: None
                height: self.texture_size[1] + dp(10)

            MDLabel:
                text: "Username: "
                bold: True
                font_size: "24sp"
                theme_text_color: "Primary"
                height: "25dp"

            MDTextField:
                id: login_username
                hint_text: "Username"
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}
            
            MDLabel:
                text: "Password: "
                bold: True
                font_size: "24sp"
                theme_text_color: "Primary"
                height: "25dp"

            MDTextField:
                id: login_password
                hint_text: "Password"
                password: True
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}

            Label:
                id: login_error
                text: ""
                color: 1, 0, 0, 1 # RED
                size_hint_y: None
                height: dp(20)

            MDBoxLayout: 
                size_hint_y: None
                height: "65dp"
                spacing: "30dp"
                pos_hint: {"center_x": 0.5, "bottom": 1}
                padding: "10dp", "25dp", "10dp", "10dp"

                MDBoxLayout:
                    size_hint_x: None
                    width: "280dp"  
                    pos_hint: {"center_x": 0.5}
                    spacing: "12dp" 

                    MDButton:
                        style: "elevated"
                        size_hint_x: None
                        width: "120dp"  
                        height: "50dp"
                        size_hint: 1, None
                        pos_hint: {"center_x": 0.5}
                        on_release: root.do_login()

                        MDButtonText:
                            text: "[b]Login[/b]"
                            color: 0.2, 0.6, 1, 1 # BLUE

                    MDButton:
                        style: "elevated"
                        size_hint_x: None
                        width: "120dp"  
                        height: "50dp"
                        size_hint: 1, None
                        pos_hint: {"center_x": 0.5}
                        on_release: root.manager.current = "create_account"

                        MDButtonText:
                            text: "[b]Create An Account[/b]"   
                            color: 0.2, 0.6, 1, 1 # BLUE        

<CreateAccountScreen>:
    name: "create_account"

    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)  # WHITE
        Rectangle:
            pos: self.pos
            size: self.size

    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"

        BoxLayout:
            orientation: "vertical" 
            height: "360dp"
            width: "640dp"
            spacing: dp(20)
            padding: dp(20)
            size_hint: 0.9, 0.9

            Label:
                text: "Sign Up"
                bold: True
                font_size: 36
                halign: "center"
                color: 0.2, 0.6, 1, 1 # BLUE
                theme_text_color: "Primary"
                size_hint_y: None
                height: self.texture_size[1] + dp(10)

            MDLabel:
                text: "Username: "
                bold: True
                font_size: "24sp"
                theme_text_color: "Primary"
                height: "25dp"

            MDTextField:
                id: signup_username
                hint_text: "Username"
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}

            MDLabel:
                text: "Email: "
                bold: True
                font_size: "24sp"
                theme_text_color: "Primary"
                height: "25dp"

            MDTextField:
                id: signup_email
                hint_text: "Email"
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}

            MDLabel:
                text: "Password: "
                bold: True
                font_size: "24sp"
                theme_text_color: "Primary"
                height: "25dp"

            MDTextField:
                id: signup_password
                hint_text: "Password"
                password: True
                size_hint_x: 0.8
                pos_hint: {"center_x": 0.5}

            Label:
                id: signup_error
                text: ""
                color: 1, 0, 0, 1

            MDButton:
                style: "elevated"
                size_hint_x: None
                width: "100dp"  
                height: "50dp"
                size_hint: 1, None
                pos_hint: {"center_x": 0.5}
                on_release: root.do_create_account()

                MDButtonText:
                    text: "[b]Create Account[/b]"
                    color: 0.2, 0.6, 1, 1 #BLUE

            MDButton:
                style: "elevated"
                size_hint_x: None
                width: "100dp"  
                height: "50dp"
                size_hint: 1, None
                pos_hint: {"center_x": 0.5}
                on_release: root.manager.current = "login"

                MDButtonText:
                    text: "[b]Back to Login[/b]"
                    color: 0.2, 0.6, 1, 1 #BLUE



        